apiVersion: apps/v1
kind: Deployment
metadata:
  name:  validator
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app:  validator
  template:
    metadata:
      labels:
        app:  validator
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}