apiVersion: v1
kind: Service
metadata:
  name: validator
  labels:
    app: app
spec:
  selector:
    app: validator
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containerPort }}